// GENERATED by app/tools/fetch-profiles.ts --groups from Bambu Studio v02.08.02.61
// (commit 926a7192574bcb9b3a732e1ec59a46d79cb45466), src/slic3r/GUI/Tab.cpp. Bambu Studio is AGPL-3.0, like this app.
// Do not edit: change the generator or the pin in slicer/upstream.lock and run it again.

export interface TabPage {
	page: string;
	groups: { group: string; keys: string[] }[];
}

export const TAB_GROUPS: Record<'process' | 'filament' | 'printer', TabPage[]> = {
	process: [
		{
			page: 'Quality',
			groups: [
				{
					group: 'Layer height',
					keys: ['layer_height', 'initial_layer_print_height', 'enable_mixed_color_sublayer']
				},
				{
					group: 'Line width',
					keys: [
						'line_width',
						'initial_layer_line_width',
						'outer_wall_line_width',
						'inner_wall_line_width',
						'top_surface_line_width',
						'sparse_infill_line_width',
						'internal_solid_infill_line_width',
						'support_line_width'
					]
				},
				{
					group: 'Seam',
					keys: [
						'seam_position',
						'seam_placement_away_from_overhangs',
						'seam_gap',
						'seam_slope_conditional',
						'scarf_angle_threshold',
						'seam_slope_entire_loop',
						'seam_slope_steps',
						'seam_slope_inner_walls',
						'override_filament_scarf_seam_setting',
						'seam_slope_type',
						'seam_slope_start_height',
						'seam_slope_gap',
						'seam_slope_min_length',
						'wipe_speed',
						'role_base_wipe_speed'
					]
				},
				{
					group: 'Precision',
					keys: [
						'slice_closing_radius',
						'resolution',
						'enable_arc_fitting',
						'xy_hole_compensation',
						'xy_contour_compensation',
						'enable_circle_compensation',
						'circle_compensation_manual_offset',
						'elefant_foot_compensation',
						'precise_outer_wall',
						'precise_z_height'
					]
				},
				{
					group: 'Ironing',
					keys: [
						'ironing_type',
						'ironing_pattern',
						'ironing_speed',
						'ironing_flow',
						'ironing_spacing',
						'ironing_inset',
						'ironing_direction'
					]
				},
				{
					group: 'Wall generator',
					keys: [
						'wall_generator',
						'wall_transition_angle',
						'wall_transition_filter_deviation',
						'wall_transition_length',
						'wall_distribution_count',
						'min_bead_width',
						'min_feature_size'
					]
				},
				{
					group: 'Advanced',
					keys: [
						'wall_sequence',
						'is_infill_first',
						'bridge_flow',
						'thick_bridges',
						'counterbore_hole_bridging',
						'print_flow_ratio',
						'top_solid_infill_flow_ratio',
						'initial_layer_flow_ratio',
						'top_one_wall_type',
						'top_area_threshold',
						'only_one_wall_first_layer',
						'detect_overhang_wall',
						'smooth_speed_discontinuity_area',
						'smooth_coefficient',
						'reduce_crossing_wall',
						'max_travel_detour_distance',
						'avoid_crossing_wall_includes_support',
						'z_direction_outwall_speed_continuous'
					]
				}
			]
		},
		{
			page: 'Strength',
			groups: [
				{
					group: 'Walls',
					keys: [
						'wall_loops',
						'alternate_extra_wall',
						'embedding_wall_into_infill',
						'detect_thin_wall'
					]
				},
				{
					group: 'Top/bottom shells',
					keys: [
						'interface_shells',
						'top_surface_pattern',
						'top_surface_density',
						'top_shell_layers',
						'top_shell_thickness',
						'top_color_penetration_layers',
						'bottom_surface_pattern',
						'bottom_surface_density',
						'bottom_shell_layers',
						'bottom_shell_thickness',
						'bottom_color_penetration_layers',
						'infill_instead_top_bottom_surfaces',
						'internal_solid_infill_pattern'
					]
				},
				{
					group: 'Sparse infill',
					keys: [
						'sparse_infill_density',
						'fill_multiline',
						'sparse_infill_pattern',
						'locked_skin_infill_pattern',
						'skin_infill_density',
						'locked_skeleton_infill_pattern',
						'skeleton_infill_density',
						'infill_lock_depth',
						'skin_infill_depth',
						'skin_infill_line_width',
						'skeleton_infill_line_width',
						'symmetric_infill_y_axis',
						'infill_shift_step',
						'sparse_infill_lattice_angle_1',
						'sparse_infill_lattice_angle_2',
						'infill_rotate_step',
						'sparse_infill_anchor',
						'sparse_infill_anchor_max',
						'filter_out_gap_fill'
					]
				},
				{
					group: 'Advanced',
					keys: [
						'infill_wall_overlap',
						'monotonic_travel_into_wall',
						'infill_direction',
						'bridge_angle',
						'minimum_sparse_infill_area',
						'infill_combination',
						'detect_narrow_internal_solid_infill',
						'ensure_vertical_shell_thickness',
						'detect_floating_vertical_shell'
					]
				}
			]
		},
		{
			page: 'Speed',
			groups: [
				{
					group: 'Initial layer speed',
					keys: ['initial_layer_speed', 'initial_layer_infill_speed']
				},
				{
					group: 'Other layers speed',
					keys: [
						'outer_wall_speed',
						'inner_wall_speed',
						'small_perimeter_speed',
						'small_perimeter_threshold',
						'sparse_infill_speed',
						'internal_solid_infill_speed',
						'vertical_shell_speed',
						'top_surface_speed',
						'enable_overhang_speed',
						'overhang_1_4_speed',
						'overhang_2_4_speed',
						'overhang_3_4_speed',
						'overhang_4_4_speed',
						'overhang_totally_speed',
						'enable_height_slowdown',
						'slowdown_start_height',
						'slowdown_start_speed',
						'slowdown_start_acc',
						'slowdown_end_height',
						'slowdown_end_speed',
						'slowdown_end_acc',
						'bridge_speed',
						'gap_infill_speed',
						'support_speed',
						'support_interface_speed'
					]
				},
				{
					group: 'Travel speed',
					keys: ['travel_speed']
				},
				{
					group: 'Acceleration',
					keys: [
						'default_acceleration',
						'travel_acceleration',
						'travel_short_distance_acceleration',
						'initial_layer_travel_acceleration',
						'initial_layer_acceleration',
						'outer_wall_acceleration',
						'inner_wall_acceleration',
						'top_surface_acceleration',
						'sparse_infill_acceleration',
						'accel_to_decel_enable',
						'accel_to_decel_factor'
					]
				},
				{
					group: 'Jerk(XY)',
					keys: [
						'default_jerk',
						'outer_wall_jerk',
						'inner_wall_jerk',
						'infill_jerk',
						'top_surface_jerk',
						'initial_layer_jerk',
						'travel_jerk',
						'max_volumetric_extrusion_rate_slope_positive',
						'max_volumetric_extrusion_rate_slope_negative'
					]
				}
			]
		},
		{
			page: 'Support',
			groups: [
				{
					group: 'Support',
					keys: [
						'enable_support',
						'support_type',
						'support_style',
						'support_threshold_angle',
						'support_on_build_plate_only',
						'support_critical_regions_only',
						'support_remove_small_overhang'
					]
				},
				{
					group: 'Raft',
					keys: ['raft_layers', 'raft_contact_distance']
				},
				{
					group: 'Support filament',
					keys: ['support_filament', 'support_interface_filament', 'support_interface_not_for_body']
				},
				{
					group: 'Support ironing',
					keys: [
						'enable_support_ironing',
						'support_ironing_pattern',
						'support_ironing_speed',
						'support_ironing_flow',
						'support_ironing_spacing',
						'support_ironing_inset',
						'support_ironing_direction'
					]
				},
				{
					group: 'Advanced',
					keys: [
						'raft_first_layer_density',
						'raft_first_layer_expansion',
						'tree_support_wall_count',
						'support_top_z_distance',
						'support_bottom_z_distance',
						'support_base_pattern',
						'support_base_pattern_spacing',
						'support_angle',
						'support_interface_top_layers',
						'support_interface_bottom_layers',
						'support_interface_pattern',
						'support_interface_spacing',
						'support_bottom_interface_spacing',
						'support_expansion',
						'support_object_xy_distance',
						'top_z_overrides_xy_distance',
						'support_object_first_layer_gap',
						'bridge_no_support',
						'max_bridge_length',
						'independent_support_layer_height'
					]
				},
				{
					group: 'Tree Support',
					keys: [
						'tree_support_branch_distance',
						'tree_support_branch_diameter',
						'tree_support_branch_angle',
						'tree_support_branch_diameter_angle'
					]
				}
			]
		},
		{
			page: 'Others',
			groups: [
				{
					group: 'Bed adhension',
					keys: [
						'skirt_loops',
						'skirt_height',
						'skirt_distance',
						'brim_type',
						'brim_width',
						'brim_object_gap'
					]
				},
				{
					group: 'Prime tower',
					keys: [
						'enable_prime_tower',
						'prime_tower_skip_points',
						'prime_tower_enable_framework',
						'prime_tower_width',
						'prime_tower_max_speed',
						'prime_tower_brim_width',
						'prime_tower_infill_gap',
						'prime_tower_rib_wall',
						'prime_tower_extra_rib_length',
						'prime_tower_rib_width',
						'prime_tower_fillet_wall',
						'enable_tower_interface_features',
						'wipe_tower_no_sparse_layers'
					]
				},
				{
					group: 'Flush options',
					keys: ['flush_into_infill', 'flush_into_objects', 'flush_into_support']
				},
				{
					group: 'Special mode',
					keys: [
						'slicing_mode',
						'print_sequence',
						'spiral_mode',
						'spiral_mode_smooth',
						'spiral_mode_max_xy_smoothing',
						'timelapse_type',
						'fuzzy_skin',
						'fuzzy_skin_mode',
						'fuzzy_skin_noise_type',
						'fuzzy_skin_point_distance',
						'fuzzy_skin_thickness',
						'fuzzy_skin_scale',
						'fuzzy_skin_octaves',
						'fuzzy_skin_persistence',
						'fuzzy_skin_first_layer'
					]
				},
				{
					group: 'Advanced',
					keys: [
						'enable_wrapping_detection',
						'enable_order_independent_overlap_carving',
						'interlocking_beam',
						'mmu_segmented_region_interlocking_depth',
						'interlocking_beam_width',
						'interlocking_orientation',
						'interlocking_beam_layer_count',
						'interlocking_depth',
						'interlocking_boundary_avoidance',
						'sparse_infill_filament',
						'solid_infill_filament',
						'wall_filament'
					]
				},
				{
					group: 'G-code output',
					keys: [
						'reduce_infill_retraction_mode',
						'gcode_add_line_number',
						'exclude_object',
						'filename_format'
					]
				},
				{
					group: 'Post-processing scripts',
					keys: ['post_process']
				},
				{
					group: 'Notes',
					keys: ['process_notes']
				}
			]
		}
	],
	filament: [
		{
			page: 'Setting Overrides',
			groups: [
				{
					group: 'Speed',
					keys: [
						'override_process_overhang_speed',
						'filament_enable_overhang_speed',
						'filament_overhang_1_4_speed',
						'filament_overhang_2_4_speed',
						'filament_overhang_3_4_speed',
						'filament_overhang_4_4_speed',
						'filament_overhang_totally_speed',
						'filament_bridge_speed'
					]
				}
			]
		},
		{
			page: 'Filament',
			groups: [
				{
					group: 'Basic information',
					keys: [
						'filament_type',
						'filament_vendor',
						'filament_soluble',
						'filament_is_support',
						'impact_strength_z',
						'default_filament_colour',
						'filament_diameter',
						'filament_adhesiveness_category',
						'filament_metal_stickiness',
						'filament_flow_ratio',
						'enable_pressure_advance',
						'pressure_advance',
						'filament_density',
						'filament_shrink',
						'filament_velocity_adaptation_factor',
						'filament_cost',
						'temperature_vitrification',
						'filament_printable',
						'filament_cooling_before_tower',
						'filament_tower_interface_pre_extrusion_dist',
						'filament_tower_interface_pre_extrusion_length',
						'filament_tower_ironing_area',
						'filament_tower_interface_purge_volume',
						'filament_tower_interface_print_temp',
						'filament_prime_volume',
						'filament_prime_volume_nc',
						'filament_change_length',
						'filament_change_length_nc',
						'filament_ramming_travel_time',
						'filament_ramming_travel_time_nc',
						'filament_pre_cooling_temperature',
						'filament_pre_cooling_temperature_nc',
						'nozzle_temperature_range_low',
						'nozzle_temperature_range_high'
					]
				},
				{
					group: 'Print temperature',
					keys: [
						'chamber_temperatures',
						'supertack_plate_temp_initial_layer',
						'supertack_plate_temp',
						'cool_plate_temp_initial_layer',
						'cool_plate_temp',
						'eng_plate_temp_initial_layer',
						'eng_plate_temp',
						'hot_plate_temp_initial_layer',
						'hot_plate_temp',
						'textured_plate_temp_initial_layer',
						'textured_plate_temp',
						'nozzle_temperature_initial_layer',
						'nozzle_temperature'
					]
				},
				{
					group: 'Volumetric speed limitation',
					keys: [
						'filament_adaptive_volumetric_speed',
						'filament_max_volumetric_speed',
						'filament_ramming_volumetric_speed',
						'filament_ramming_volumetric_speed_nc'
					]
				},
				{
					group: 'Filament scarf seam settings',
					keys: [
						'filament_scarf_seam_type',
						'filament_scarf_height',
						'filament_scarf_gap',
						'filament_scarf_length'
					]
				}
			]
		},
		{
			page: 'Cooling',
			groups: [
				{
					group: 'Part cooling fan',
					keys: [
						'close_fan_the_first_x_layers',
						'first_x_layer_part_fan_speed',
						'full_fan_speed_layer',
						'fan_min_speed',
						'fan_cooling_layer_time',
						'fan_max_speed',
						'slow_down_layer_time',
						'reduce_fan_stop_start_freq',
						'slow_down_for_layer_cooling',
						'no_slow_down_for_cooling_on_outwalls',
						'cooling_slowdown_logic',
						'cooling_perimeter_transition_distance',
						'slow_down_min_speed',
						'enable_overhang_bridge_fan',
						'overhang_fan_threshold',
						'overhang_threshold_participating_cooling',
						'overhang_fan_speed',
						'pre_start_fan_time',
						'ironing_fan_speed'
					]
				},
				{
					group: 'Auxiliary part cooling fan',
					keys: [
						'close_additional_fan_first_x_layers',
						'first_x_layer_fan_speed',
						'additional_fan_full_speed_layer',
						'additional_cooling_fan_speed'
					]
				},
				{
					group: 'Exhaust fan',
					keys: [
						'activate_air_filtration',
						'during_print_exhaust_fan_speed',
						'complete_print_exhaust_fan_speed'
					]
				}
			]
		},
		{
			page: 'Advanced',
			groups: [
				{
					group: 'Filament start G-code',
					keys: ['filament_start_gcode']
				},
				{
					group: 'Filament end G-code',
					keys: ['filament_end_gcode']
				}
			]
		},
		{
			page: 'Notes',
			groups: [
				{
					group: 'Notes',
					keys: ['filament_notes']
				}
			]
		},
		{
			page: 'Multi Filament',
			groups: [
				{
					group: 'Multi Filament',
					keys: [
						'filament_flush_temp',
						'filament_flush_temp_fast',
						'filament_flush_volumetric_speed',
						'long_retractions_when_ec',
						'retraction_distances_when_ec'
					]
				}
			]
		}
	],
	printer: [
		{
			page: 'Basic information',
			groups: [
				{
					group: 'Printable space',
					keys: ['bed_exclude_area', 'printable_height', 'best_object_pos']
				},
				{
					group: 'Advanced',
					keys: [
						'printer_structure',
						'gcode_flavor',
						'thumbnail_size',
						'scan_first_layer',
						'print_in_clockwise',
						'use_relative_e_distances',
						'use_firmware_retraction',
						'bed_temperature_formula',
						'machine_load_filament_time',
						'machine_unload_filament_time',
						'machine_switch_extruder_time',
						'machine_hotend_change_time'
					]
				},
				{
					group: 'Extruder Clearance',
					keys: [
						'extruder_clearance_max_radius',
						'extruder_clearance_dist_to_rod',
						'extruder_clearance_height_to_rod',
						'extruder_clearance_height_to_lid'
					]
				},
				{
					group: 'Accessory',
					keys: [
						'nozzle_type',
						'auxiliary_fan',
						'fan_direction',
						'support_chamber_temp_control',
						'support_air_filtration',
						'cooling_filter_enabled'
					]
				}
			]
		},
		{
			page: 'Machine gcode',
			groups: [
				{
					group: 'Machine start G-code',
					keys: ['machine_start_gcode']
				},
				{
					group: 'Machine end G-code',
					keys: ['machine_end_gcode']
				},
				{
					group: 'Printing by object G-code',
					keys: ['printing_by_object_gcode']
				},
				{
					group: 'Before layer change G-code',
					keys: ['before_layer_change_gcode']
				},
				{
					group: 'Layer change G-code',
					keys: ['layer_change_gcode']
				},
				{
					group: 'Time lapse G-code',
					keys: ['time_lapse_gcode']
				},
				{
					group: 'Clumping Detection G-code',
					keys: ['wrapping_detection_gcode']
				},
				{
					group: 'Change filament G-code',
					keys: ['change_filament_gcode']
				},
				{
					group: 'Pause G-code',
					keys: ['machine_pause_gcode']
				},
				{
					group: 'Template Custom G-code',
					keys: ['template_custom_gcode']
				}
			]
		},
		{
			page: 'Notes',
			groups: [
				{
					group: 'Notes',
					keys: ['printer_notes']
				}
			]
		},
		{
			page: 'Motion ability',
			groups: [
				{
					group: 'Acceleration limitation',
					keys: [
						'machine_max_acceleration_',
						'machine_max_acceleration_extruding',
						'machine_max_acceleration_retracting',
						'machine_max_acceleration_travel',
						'machine_max_printed_mass'
					]
				},
				{
					group: 'Jerk limitation',
					keys: ['machine_max_jerk_']
				}
			]
		},
		{
			page: 'Extruder',
			groups: [
				{
					group: 'Basic information',
					keys: [
						'extruder_type',
						'nozzle_diameter',
						'nozzle_volume',
						'extruder_printable_height',
						'extruder_printable_area'
					]
				},
				{
					group: 'Layer height limits',
					keys: ['min_layer_height', 'max_layer_height']
				},
				{
					group: 'Position',
					keys: ['extruder_offset']
				},
				{
					group: 'Retraction',
					keys: [
						'retraction_length',
						'z_hop',
						'retract_lift_above',
						'retract_lift_below',
						'z_hop_types',
						'retraction_speed',
						'deretraction_speed',
						'retract_restart_extra',
						'retraction_minimum_travel',
						'retract_when_changing_layer',
						'wipe',
						'wipe_distance',
						'retract_before_wipe'
					]
				},
				{
					group: 'Retraction when switching material',
					keys: [
						'retract_length_toolchange',
						'retract_restart_extra_toolchange',
						'long_retractions_when_cut',
						'retraction_distances_when_cut'
					]
				}
			]
		}
	]
};
