import { chromium } from '@playwright/test';
const [,, id, out, w] = process.argv;
const b = await chromium.launch({ channel: 'chrome', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: Number(w || 1400), height: 1000 } });
await p.addInitScript(() => sessionStorage.setItem('print-lab-profile', 'all'));
p.on('pageerror', (e) => console.log('pageerror', e.message));
p.on('console', (m) => { if (m.type() === 'error') console.log('console', m.text()); });
await p.goto(`http://127.0.0.1:5491/printers/${id}`);
await p.locator('html[data-ready]').waitFor({ state: 'attached', timeout: 60000 });
await p.waitForTimeout(2500);
await p.screenshot({ path: out, fullPage: true });
await b.close();
