// GENERATED by app/tools/gen-printer-models.ts from Bambu Studio v02.08.02.61
// (commit 926a7192574bcb9b3a732e1ec59a46d79cb45466), resources/printers/*.json. Bambu Studio is AGPL-3.0, like this app.
// Do not edit: change the generator or the pin in slicer/upstream.lock and run it again.

export const UPSTREAM_PRINTERS = {
	tag: 'v02.08.02.61',
	commit: '926a7192574bcb9b3a732e1ec59a46d79cb45466'
} as const;

/** Capability flags as the upstream files state them (keys of `Capabilities` in models.ts). */
export type GeneratedCaps = Record<string, boolean>;

export interface GeneratedModel {
	code: string;
	displayName: string;
	enclosed: boolean;
	nozzleTempMax: number;
	bedTempMax: number;
	chamberTempMax: number | null;
	/** print.ipcam.liveview.local ("local" = the port-6000 JPEG stream). */
	liveviewLocal: string | null;
	ftpFolder: string | null;
	caps: GeneratedCaps;
	/** Later firmware keys, ascending; Bambu Studio itself only reads "00.00.00.00" at this tag. */
	firmwareCaps: { from: string; caps: GeneratedCaps }[];
}

export const GENERATED_MODELS: Record<string, GeneratedModel> = {
	'BL-P001': {
		code: 'BL-P001',
		displayName: 'Bambu Lab X1 Carbon',
		enclosed: true,
		nozzleTempMax: 300,
		bedTempMax: 120,
		chamberTempMax: null,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: false,
			auxFan: true,
			chamberFan: true,
			lidar: true,
			aiMonitoring: false,
			firstLayerInspect: true,
			buildPlateMarkerDetect: false,
			amsHumidity: false,
			amsSwitchCommand: false,
			timelapse: true,
			sendToSd: false,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: false,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: [
			{
				from: '01.01.01.00',
				caps: {
					aiMonitoring: true,
					buildPlateMarkerDetect: true,
					amsHumidity: true,
					sendToSd: true
				}
			},
			{
				from: '01.05.06.01',
				caps: {
					amsSwitchCommand: true
				}
			},
			{
				from: '01.06.06.00',
				caps: {
					userPreset: true
				}
			}
		]
	},
	'BL-P002': {
		code: 'BL-P002',
		displayName: 'Bambu Lab X1',
		enclosed: true,
		nozzleTempMax: 300,
		bedTempMax: 120,
		chamberTempMax: null,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: false,
			auxFan: true,
			chamberFan: true,
			lidar: true,
			aiMonitoring: false,
			firstLayerInspect: true,
			buildPlateMarkerDetect: false,
			amsHumidity: false,
			amsSwitchCommand: false,
			timelapse: true,
			sendToSd: false,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: false,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: [
			{
				from: '01.01.01.00',
				caps: {
					aiMonitoring: true,
					buildPlateMarkerDetect: true,
					amsHumidity: true,
					sendToSd: true
				}
			},
			{
				from: '01.05.06.01',
				caps: {
					amsSwitchCommand: true
				}
			},
			{
				from: '01.06.06.00',
				caps: {
					userPreset: true
				}
			}
		]
	},
	C11: {
		code: 'C11',
		displayName: 'Bambu Lab P1P',
		enclosed: false,
		nozzleTempMax: 300,
		bedTempMax: 100,
		chamberTempMax: null,
		liveviewLocal: 'local',
		ftpFolder: 'sdcard/',
		caps: {
			chamberTempEdit: false,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: false,
			firstLayerInspect: false,
			buildPlateMarkerDetect: false,
			amsHumidity: true,
			amsSwitchCommand: false,
			timelapse: true,
			sendToSd: false,
			printWithoutSd: false,
			motorNoiseCali: false,
			flowCalibration: false,
			autoFlowCalibration: false,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: false,
			bedLeveling: true
		},
		firmwareCaps: [
			{
				from: '01.02.00.00',
				caps: {
					sendToSd: true
				}
			},
			{
				from: '01.02.99.10',
				caps: {
					amsSwitchCommand: true
				}
			},
			{
				from: '01.04.50.01',
				caps: {
					userPreset: true
				}
			}
		]
	},
	C12: {
		code: 'C12',
		displayName: 'Bambu Lab P1S',
		enclosed: true,
		nozzleTempMax: 300,
		bedTempMax: 100,
		chamberTempMax: null,
		liveviewLocal: 'local',
		ftpFolder: 'sdcard/',
		caps: {
			chamberTempEdit: false,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: false,
			firstLayerInspect: false,
			buildPlateMarkerDetect: false,
			amsHumidity: true,
			amsSwitchCommand: false,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: false,
			motorNoiseCali: false,
			flowCalibration: false,
			autoFlowCalibration: false,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: false,
			bedLeveling: true
		},
		firmwareCaps: [
			{
				from: '01.02.99.10',
				caps: {
					amsSwitchCommand: true
				}
			},
			{
				from: '01.04.50.01',
				caps: {
					userPreset: true
				}
			}
		]
	},
	C13: {
		code: 'C13',
		displayName: 'Bambu Lab X1E',
		enclosed: true,
		nozzleTempMax: 320,
		bedTempMax: 110,
		chamberTempMax: 60,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: true,
			auxFan: true,
			chamberFan: true,
			lidar: true,
			aiMonitoring: true,
			firstLayerInspect: true,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: false,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	N1: {
		code: 'N1',
		displayName: 'Bambu Lab A1 mini',
		enclosed: false,
		nozzleTempMax: 300,
		bedTempMax: 80,
		chamberTempMax: null,
		liveviewLocal: 'local',
		ftpFolder: 'sdcard/',
		caps: {
			chamberTempEdit: false,
			auxFan: false,
			chamberFan: false,
			lidar: false,
			aiMonitoring: false,
			firstLayerInspect: false,
			buildPlateMarkerDetect: false,
			amsHumidity: false,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: false,
			motorNoiseCali: true,
			flowCalibration: true,
			autoFlowCalibration: false,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: false,
			bedLeveling: true
		},
		firmwareCaps: [
			{
				from: '01.01.50.01',
				caps: {
					userPreset: true
				}
			}
		]
	},
	N2S: {
		code: 'N2S',
		displayName: 'Bambu Lab A1',
		enclosed: false,
		nozzleTempMax: 300,
		bedTempMax: 100,
		chamberTempMax: null,
		liveviewLocal: 'local',
		ftpFolder: 'sdcard/',
		caps: {
			chamberTempEdit: false,
			auxFan: false,
			chamberFan: false,
			lidar: false,
			aiMonitoring: false,
			firstLayerInspect: false,
			buildPlateMarkerDetect: false,
			amsHumidity: false,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: false,
			motorNoiseCali: true,
			flowCalibration: true,
			autoFlowCalibration: false,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: false,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	N6: {
		code: 'N6',
		displayName: 'Bambu Lab X2D',
		enclosed: true,
		nozzleTempMax: 300,
		bedTempMax: 120,
		chamberTempMax: 65,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: true,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: true,
			firstLayerInspect: false,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: true,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	N7: {
		code: 'N7',
		displayName: 'Bambu Lab P2S',
		enclosed: true,
		nozzleTempMax: 300,
		bedTempMax: 110,
		chamberTempMax: null,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: false,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: true,
			firstLayerInspect: false,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	N9: {
		code: 'N9',
		displayName: 'Bambu Lab A2L',
		enclosed: false,
		nozzleTempMax: 300,
		bedTempMax: 80,
		chamberTempMax: null,
		liveviewLocal: 'local',
		ftpFolder: 'sdcard/',
		caps: {
			chamberTempEdit: false,
			auxFan: false,
			chamberFan: false,
			lidar: false,
			aiMonitoring: false,
			firstLayerInspect: false,
			buildPlateMarkerDetect: false,
			amsHumidity: false,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: false,
			motorNoiseCali: true,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: false,
			bedLeveling: true
		},
		firmwareCaps: [
			{
				from: '01.01.50.01',
				caps: {
					userPreset: true
				}
			}
		]
	},
	O1C: {
		code: 'O1C',
		displayName: 'Bambu Lab H2C',
		enclosed: true,
		nozzleTempMax: 350,
		bedTempMax: 120,
		chamberTempMax: 65,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: true,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: true,
			firstLayerInspect: false,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: true,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	O1C2: {
		code: 'O1C2',
		displayName: 'Bambu Lab H2C',
		enclosed: true,
		nozzleTempMax: 350,
		bedTempMax: 120,
		chamberTempMax: 65,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: true,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: true,
			firstLayerInspect: false,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: true,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	O1D: {
		code: 'O1D',
		displayName: 'Bambu Lab H2D',
		enclosed: true,
		nozzleTempMax: 350,
		bedTempMax: 120,
		chamberTempMax: 65,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: true,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: true,
			firstLayerInspect: false,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: true,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	O1E: {
		code: 'O1E',
		displayName: 'Bambu Lab H2D Pro',
		enclosed: true,
		nozzleTempMax: 350,
		bedTempMax: 120,
		chamberTempMax: 65,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: true,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: true,
			firstLayerInspect: false,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: true,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	},
	O1S: {
		code: 'O1S',
		displayName: 'Bambu Lab H2S',
		enclosed: true,
		nozzleTempMax: 350,
		bedTempMax: 120,
		chamberTempMax: 65,
		liveviewLocal: null,
		ftpFolder: null,
		caps: {
			chamberTempEdit: true,
			auxFan: true,
			chamberFan: true,
			lidar: false,
			aiMonitoring: true,
			firstLayerInspect: false,
			buildPlateMarkerDetect: true,
			amsHumidity: true,
			amsSwitchCommand: true,
			timelapse: true,
			sendToSd: true,
			printWithoutSd: true,
			motorNoiseCali: false,
			flowCalibration: true,
			autoFlowCalibration: true,
			nozzleOffsetCalibration: false,
			userPreset: false,
			chamberTempDisplay: true,
			bedLeveling: true
		},
		firmwareCaps: []
	}
};
