// The printer model catalogue: every Bambu Lab model the app knows, what it can do, and how to reach it.
// Two layers: models.generated.ts holds what Bambu Studio's resources/printers/<code>.json files say
// (regenerated by app/tools/gen-printer-models.ts at the pin in slicer/upstream.lock); this file adds
// the facts those files do not carry, each citing its source. Runtime evidence wins over both: the
// feature bits a printer reports (PrinterSnapshot.firmwareSupport) override these for what they cover.
import { GENERATED_MODELS, type GeneratedModel } from './models.generated';
import type { VersionModule } from './status';

export const MODEL_CODES = [
	'BL-P001',
	'BL-P002',
	'C13',
	'C11',
	'C12',
	'N1',
	'N2S',
	'N9',
	'N7',
	'N6',
	'O1D',
	'O1E',
	'O1S',
	'O1C',
	'O1C2'
] as const;
export type ModelCode = (typeof MODEL_CODES)[number];
export type Series = 'X1' | 'P1' | 'A1' | 'A2' | 'P2' | 'H2' | 'X2';
/**
 * How the live camera is reached on the LAN. The catalogue gives the default; the live report decides
 * (`ipcam.rtsp_url`: "rtsps://…" → rtsps, "rtsp://…" → rtsp on port 554, "disable" → off until the
 * user enables LAN liveview), as Bambu Studio DeviceManager.cpp ~3450 does.
 */
export type CameraProtocol = 'rtsps' | 'rtsp' | 'jpeg6000' | 'none';

export interface Capabilities {
	/** support_chamber_temp_display, else support_chamber (Bambu Studio DevConfig.cpp). */
	chamberTempDisplay: boolean;
	/** support_chamber_temp_edit. */
	chamberTempEdit: boolean;
	/** support_aux_fan. */
	auxFan: boolean;
	/** support_chamber_fan. */
	chamberFan: boolean;
	/** ha-bambulab Features.SECONDARY_AUX_FAN (P2S, X2D). */
	secondaryAuxFan: boolean;
	/** ha-bambulab Features.AIRDUCT_MODE (H2, P2S, X2D). */
	airductMode: boolean;
	/** support_lidar_calibration. */
	lidar: boolean;
	/** support_ai_monitoring. */
	aiMonitoring: boolean;
	/** support_first_layer_inspect. */
	firstLayerInspect: boolean;
	/** support_build_plate_marker_detect. */
	buildPlateMarkerDetect: boolean;
	/** support_ams_humidity. */
	amsHumidity: boolean;
	/** ha-bambulab Features.AMS_DRYING (per-model firmware gates). */
	amsDrying: boolean;
	/** ha-bambulab Features.AMS_DRYING_SETTINGS. */
	amsDryingSettings: boolean;
	/** support_command_ams_switch. */
	amsSwitchCommand: boolean;
	/** ha-bambulab Features.AMS_READ_RFID_COMMAND. */
	amsReadRfid: boolean;
	/** ha-bambulab dual_nozzle_printers (H2C, H2D, H2D Pro, X2D). */
	dualNozzle: boolean;
	/** ha-bambulab Features.EXTRUDER_TOOL (H2 laser/cutter head). */
	extruderTool: boolean;
	/** lights_report "work_light" (X1 series; the X2D reports it too: ha-bambulab MOCK-X2D.json). */
	workLight: boolean;
	/** ha-bambulab Features.CHAMBER_LIGHT_2 (H2, X2). */
	chamberLight2: boolean;
	/** ha-bambulab Features.HEATBED_LIGHT (H2). */
	heatbedLight: boolean;
	/** ha-bambulab Features.DOOR_SENSOR (with firmware gates). */
	doorSensor: boolean;
	/** ha-bambulab Features.PROMPT_SOUND (A1, A2, H2, P2, X2; also needs Developer Mode). */
	promptSound: boolean;
	/** support_timelapse. */
	timelapse: boolean;
	/** support_send_to_sd. */
	sendToSd: boolean;
	/** support_print_without_sd. */
	printWithoutSd: boolean;
	/** support_motor_noise_cali. */
	motorNoiseCali: boolean;
	/** support_flow_calibration. */
	flowCalibration: boolean;
	/** support_auto_flow_calibration. */
	autoFlowCalibration: boolean;
	/** support_nozzle_offset_calibration. */
	nozzleOffsetCalibration: boolean;
	/** support_bed_leveling > 0. */
	bedLeveling: boolean;
	/** support_user_preset. */
	userPreset: boolean;
	/** ha-bambulab Features.K_VALUE (A1, A2, P1). */
	kValueInReport: boolean;
	/** ha-bambulab Features.ACTIVE_CHAMBER_HEATER (X1E, H2, X2). */
	activeChamberHeater: boolean;
	/** ha-bambulab Features.FIRE_ALARM_BUZZER (H2); buzzer_ctrl. */
	fireAlarmBuzzer: boolean;
	/** ha-bambulab Features.HOTEND_RACK (H2C with a rack reported); also fun bit 60 at runtime. */
	hotendRack: boolean;
	/** P1 firmware ≥ 01.07.00.00 ignores LAN commands while also cloud-connected (ha-bambulab Features.HYBRID_MODE_BLOCKS_CONTROL): warn, do not block. */
	hybridModeBlocksControl: boolean;
	/** Firmware where Developer Mode is required for LAN control (ha-bambulab Features.MQTT_ENCRYPTION_FIRMWARE): drives the setup help text. */
	developerModeRequired: boolean;
}

export interface PrinterModel {
	code: ModelCode;
	/** Bambu Studio machine model name, e.g. "Bambu Lab X1 Carbon" (also the profile machine_model name). */
	name: string;
	/** "X1C", "P1S", "A1 mini", "H2D", "X2D"… */
	short: string;
	series: Series;
	/** Serial-number prefix Bambu's HMS data uses for this model ("00M", "094"…), null when unknown. */
	hmsDevice: string | null;
	/** X1 series send full push_status; others send deltas (OpenBambuAPI mqtt.md "push_status"). */
	reports: 'full' | 'delta';
	camera: CameraProtocol;
	nozzles: 1 | 2;
	/**
	 * project_file url form: 'sdcard' → file:///sdcard/<name>, 'ftp' → ftp:///<name>. The references
	 * disagree for some models: see PRINT_URL_UNVERIFIED.
	 */
	printUrl: 'sdcard' | 'ftp';
	/** printer_is_enclosed. */
	enclosed: boolean;
	/** nozzle_temp_range[1]. */
	nozzleTempMax: number;
	/** bed_temp_range[1] / bed_temperature_limit, else Bambu Studio's BED_TEMP_LIMIT (120). */
	bedTempMax: number;
	/** support_chamber_temp_edit_range[1]. */
	chamberTempMax: number | null;
	/** At firmware 00.00.00.00. */
	caps: Capabilities;
	/** Version-gated overrides, ascending by firmware version. */
	firmwareCaps: { from: string; caps: Partial<Capabilities> }[];
}

/**
 * Models whose project_file url form is not settled. ha-bambulab (0e027ff) contradicts itself:
 * const.py LEGACY_SDCARD_PRINTERS (defined, never used) implies ftp:/// for every model not listed,
 * while the path that runs, coordinator.py _service_call_print_project_file ~720–727, sends ftp:///
 * only for the H2C, H2S and H2D and file:///sdcard/ for everything else, these four included. We keep
 * ftp:/// and BambuPrinter.startPrint retries once with file:///sdcard/ (the upload lands in the
 * storage root, which both forms name), logging which one worked so real diagnostics can settle it.
 */
export const PRINT_URL_UNVERIFIED: ReadonlySet<ModelCode> = new Set(['N9', 'N7', 'N6', 'O1E']);

/** Hand-written columns, from the verified table in docs/parity/PLAN.md 4.1 / 8.1. */
const TABLE: Record<
	ModelCode,
	Pick<PrinterModel, 'short' | 'series' | 'hmsDevice' | 'camera' | 'nozzles' | 'printUrl'>
> = {
	// HMS prefixes: ha-bambulab scripts/update_error_text.py _DEVICE_TYPES; null = not verified yet (hms package fills them).
	'BL-P001': {
		short: 'X1C',
		series: 'X1',
		hmsDevice: '00M',
		camera: 'rtsps',
		nozzles: 1,
		printUrl: 'sdcard'
	},
	'BL-P002': {
		short: 'X1',
		series: 'X1',
		hmsDevice: '00M',
		camera: 'rtsps',
		nozzles: 1,
		printUrl: 'sdcard'
	},
	C13: {
		short: 'X1E',
		series: 'X1',
		hmsDevice: '03W',
		camera: 'rtsps',
		nozzles: 1,
		printUrl: 'sdcard'
	},
	C11: {
		short: 'P1P',
		series: 'P1',
		hmsDevice: '01S',
		camera: 'jpeg6000',
		nozzles: 1,
		printUrl: 'sdcard'
	},
	C12: {
		short: 'P1S',
		series: 'P1',
		hmsDevice: '01P',
		camera: 'jpeg6000',
		nozzles: 1,
		printUrl: 'sdcard'
	},
	N1: {
		short: 'A1 mini',
		series: 'A1',
		hmsDevice: '030',
		camera: 'jpeg6000',
		nozzles: 1,
		printUrl: 'sdcard'
	},
	N2S: {
		short: 'A1',
		series: 'A1',
		hmsDevice: '039',
		camera: 'jpeg6000',
		nozzles: 1,
		printUrl: 'sdcard'
	},
	N9: {
		short: 'A2L',
		series: 'A2',
		hmsDevice: null,
		camera: 'jpeg6000',
		nozzles: 1,
		printUrl: 'ftp'
	},
	N7: {
		short: 'P2S',
		series: 'P2',
		hmsDevice: '22E',
		camera: 'rtsps',
		nozzles: 1,
		printUrl: 'ftp'
	},
	N6: { short: 'X2D', series: 'X2', hmsDevice: null, camera: 'rtsps', nozzles: 2, printUrl: 'ftp' },
	O1D: {
		short: 'H2D',
		series: 'H2',
		hmsDevice: '094',
		camera: 'rtsps',
		nozzles: 2,
		printUrl: 'ftp'
	},
	O1E: {
		short: 'H2D Pro',
		series: 'H2',
		hmsDevice: null,
		camera: 'rtsps',
		nozzles: 2,
		printUrl: 'ftp'
	},
	O1S: {
		short: 'H2S',
		series: 'H2',
		hmsDevice: '093',
		camera: 'rtsps',
		nozzles: 1,
		printUrl: 'ftp'
	},
	O1C: {
		short: 'H2C',
		series: 'H2',
		hmsDevice: null,
		camera: 'rtsps',
		nozzles: 2,
		printUrl: 'ftp'
	},
	O1C2: {
		short: 'H2C',
		series: 'H2',
		hmsDevice: null,
		camera: 'rtsps',
		nozzles: 2,
		printUrl: 'ftp'
	}
};

// Model groups as ha-bambulab's Device.supports_feature names them (pybambu/models.py).
const A1: ModelCode[] = ['N1', 'N2S'];
const A2: ModelCode[] = ['N9'];
const H2: ModelCode[] = ['O1C', 'O1C2', 'O1D', 'O1E', 'O1S'];
const P1: ModelCode[] = ['C11', 'C12'];
const P2: ModelCode[] = ['N7'];
const X1: ModelCode[] = ['BL-P001', 'BL-P002'];
const X1E: ModelCode[] = ['C13'];
const X2: ModelCode[] = ['N6'];
const H2C: ModelCode[] = ['O1C', 'O1C2'];
const in_ = (code: ModelCode, ...groups: ModelCode[][]) => groups.some((g) => g.includes(code));

type Gate = { from: string } | boolean;
/** A capability that is true on some models from a firmware version on (ha-bambulab supports_sw_version). */
function gate(code: ModelCode, rules: [ModelCode[], Gate][], otherwise: boolean): Gate {
	for (const [group, rule] of rules) if (group.includes(code)) return rule;
	return otherwise;
}

/** ha-bambulab Device.supports_feature, per model (pybambu/models.py at 0e027ff). */
function haFacts(code: ModelCode): Record<string, Gate> {
	return {
		secondaryAuxFan: in_(code, P2, X2),
		airductMode: in_(code, H2, P2, X2),
		amsDrying: gate(
			code,
			[
				[A1, { from: '01.06.10.33' }],
				[P1, { from: '01.07.50.18' }],
				[X1E, false],
				[X1, { from: '01.08.50.18' }]
			],
			true
		),
		amsDryingSettings: gate(
			code,
			[
				[P2, { from: '01.01.50.40' }],
				[H2C, { from: '01.01.50.00' }]
			],
			false
		),
		amsReadRfid: gate(
			code,
			[
				[A1, { from: '01.06.00.00' }],
				[P1, { from: '01.08.01.00' }],
				[X1E, false],
				[X1, { from: '01.09.00.00' }]
			],
			true
		),
		dualNozzle: in_(code, ['O1C', 'O1C2', 'O1D', 'O1E', 'N6']),
		extruderTool: in_(code, H2, X2),
		workLight: in_(code, X1, X1E, X2),
		chamberLight2: in_(code, H2, X2),
		heatbedLight: in_(code, H2),
		doorSensor: gate(
			code,
			[
				[H2, true],
				[P2, true],
				[X2, true],
				[X1E, { from: '01.01.02.00' }],
				[X1, { from: '01.07.00.00' }]
			],
			false
		),
		promptSound: in_(code, A1, A2, H2, P2, X2),
		kValueInReport: in_(code, A1, A2, P1),
		activeChamberHeater: in_(code, X1E, H2, X2),
		fireAlarmBuzzer: in_(code, H2),
		hotendRack: in_(code, H2C),
		hybridModeBlocksControl: gate(code, [[P1, { from: '01.07.00.00' }]], false),
		developerModeRequired: gate(
			code,
			[
				[A1, { from: '01.05.00.00' }],
				[['O1D', 'O1E'], { from: '01.01.00.00' }],
				[P1, { from: '01.08.02.00' }],
				[X1E, false],
				[X1, { from: '01.08.50.32' }]
			],
			true
		)
	};
}

function build(code: ModelCode): PrinterModel {
	const g: GeneratedModel | undefined = GENERATED_MODELS[code];
	if (!g) throw new Error(`No capability data for ${code}; run tools/gen-printer-models.ts.`);
	const facts = haFacts(code);
	const base = { ...g.caps } as Record<string, boolean>;
	const gated: { from: string; caps: Partial<Capabilities> }[] = g.firmwareCaps.map((f) => ({
		from: f.from,
		caps: f.caps as Partial<Capabilities>
	}));
	for (const [key, rule] of Object.entries(facts)) {
		base[key] = rule === true;
		if (typeof rule === 'object')
			gated.push({ from: rule.from, caps: { [key]: true } as Partial<Capabilities> });
	}
	gated.sort((a, b) => compareFirmware(a.from, b.from));
	return {
		code,
		name: g.displayName,
		...TABLE[code],
		reports: in_(code, X1, X1E) ? 'full' : 'delta',
		enclosed: g.enclosed,
		nozzleTempMax: g.nozzleTempMax,
		bedTempMax: g.bedTempMax,
		chamberTempMax: g.chamberTempMax,
		caps: base as unknown as Capabilities,
		firmwareCaps: gated
	};
}

export const PRINTER_MODELS = Object.fromEntries(MODEL_CODES.map((c) => [c, build(c)])) as Record<
	ModelCode,
	PrinterModel
>;

export const isModelCode = (code: unknown): code is ModelCode =>
	typeof code === 'string' && (MODEL_CODES as readonly string[]).includes(code);

export function modelByCode(code: string): PrinterModel | null {
	return isModelCode(code) ? PRINTER_MODELS[code] : null;
}

/** Models grouped by series, in catalogue order (for pickers). */
export function modelsBySeries(): { series: Series; models: PrinterModel[] }[] {
	const out: { series: Series; models: PrinterModel[] }[] = [];
	for (const code of MODEL_CODES) {
		const m = PRINTER_MODELS[code];
		// O1C and O1C2 are the same printer to people; offer one.
		if (code === 'O1C') continue;
		const group = out.find((g) => g.series === m.series);
		if (group) group.models.push(m);
		else out.push({ series: m.series, models: [m] });
	}
	return out;
}

/** Whether a file sliced for `sliced` prints on a `printer` (the H2C pair O1C/O1C2 either way). */
export function sameModel(sliced: string, printer: string): boolean {
	if (sliced === printer) return true;
	return H2C.includes(sliced as ModelCode) && H2C.includes(printer as ModelCode);
}

/** A model's short name for messages ("the P1S"), or the raw code when unknown. */
export function modelShort(code: string): string {
	return modelByCode(code)?.short ?? code;
}

/** get_version product_name → model (ha-bambulab utils.get_printer_type product_map). */
const PRODUCT_NAMES: Record<string, ModelCode> = {
	'Bambu Lab A1': 'N2S',
	'Bambu Lab A1 mini': 'N1',
	'Bambu Lab A2L': 'N9',
	'Bambu Lab P1P': 'C11',
	'Bambu Lab P1S': 'C12',
	'Bambu Lab P2S': 'N7',
	// O1C and O1C2 cannot be told apart from the product name; O1C2 is the model id profiles use.
	'Bambu Lab H2C': 'O1C2',
	'Bambu Lab H2D': 'O1D',
	'Bambu Lab H2D Pro': 'O1E',
	'Bambu Lab H2S': 'O1S',
	'Bambu Lab X2D': 'N6',
	// ha-bambulab MOCK-X1CMULTIAMS.json: the X1C's ota module says "Bambu Lab X1-Carbon".
	'Bambu Lab X1-Carbon': 'BL-P001',
	'Bambu Lab X1 Carbon': 'BL-P001',
	'Bambu Lab X1': 'BL-P002',
	'Bambu Lab X1E': 'C13'
};

/**
 * X1-series printers announce a dev_type name in SSDP DevModel, not their code (Bambu Studio
 * DeviceCore/DevConfigUtil.h _parse_printer_type, called from DevManager.cpp on_machine_alive).
 */
const SSDP_ALIASES: Record<string, ModelCode> = {
	'3DPrinter-X1-Carbon': 'BL-P001',
	'3DPrinter-X1': 'BL-P002'
};

/**
 * Model from SSDP DevModel, get_version product_name, or the older AP/project_name heuristics
 * (ha-bambulab utils.get_printer_type). The H2C pair O1C/O1C2 cannot be told apart from
 * product_name: SSDP DevModel wins, else O1C2.
 */
export function detectModel(input: {
	ssdpModel?: string;
	productName?: string;
	modules?: VersionModule[];
}): ModelCode | null {
	const ssdp = input.ssdpModel?.trim();
	if (ssdp && SSDP_ALIASES[ssdp]) return SSDP_ALIASES[ssdp];
	if (ssdp && isModelCode(ssdp)) return ssdp as ModelCode;
	if (input.productName) {
		const hit = PRODUCT_NAMES[input.productName.trim()];
		if (hit) return hit;
	}
	const modules = input.modules ?? [];
	for (const m of modules) {
		const hit = PRODUCT_NAMES[m.product.trim()];
		if (hit) return hit;
	}
	// Legacy: the AP board's hw_ver plus project_name (carried in `product` for these older reports).
	const ap = modules.find((m) => m.hw.startsWith('AP0'));
	if (ap) {
		const project = ap.product;
		if (ap.hw === 'AP02') return 'C13';
		if (project === 'N1') return 'N1';
		if (ap.hw === 'AP04' && project === 'C11') return 'C11';
		if (ap.hw === 'AP04' && project === 'C12') return 'C12';
		if (ap.hw === 'AP05' && project === 'N2S') return 'N2S';
		if (ap.hw === 'AP05' && project === '' && modules.some((m) => m.name === 'rv1126'))
			return 'BL-P001';
	}
	return null;
}

/** Compares "01.07.50.18"-style versions (missing or odd parts count as 0). */
export function compareFirmware(a: string, b: string): number {
	const pa = a.split('.').map((p) => parseInt(p, 10) || 0);
	const pb = b.split('.').map((p) => parseInt(p, 10) || 0);
	for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
		const d = (pa[i] ?? 0) - (pb[i] ?? 0);
		if (d) return d < 0 ? -1 : 1;
	}
	return 0;
}

/** Capabilities for a model at a firmware version (base + every firmwareCaps entry whose `from` ≤ version). */
export function capabilitiesFor(code: ModelCode, firmware: string | null): Capabilities {
	const model = PRINTER_MODELS[code];
	const caps = { ...model.caps };
	if (!firmware) return caps;
	// ha-bambulab supports_sw_version: X1Plus firmware (99.x) behaves like 01.08.02.00.
	const version = compareFirmware(firmware, '99.00.00.00') >= 0 ? '01.08.02.00' : firmware;
	for (const f of model.firmwareCaps)
		if (compareFirmware(f.from, version) <= 0) Object.assign(caps, f.caps);
	return caps;
}
